#!/bin/bash

if [ $1 = "build" ]; then
  ruby $WEBSITE/compiler/make.rb
fi

if [ $1 = "build-prod" ]; then
  PROD=true ruby $WEBSITE/compiler/make.rb
fi

if [ $1 = "deploy" ]; then
  sh $WEBSITE/infra/deploy.sh
fi

if [ $1 = "now" ]; then
  PREV_NOW_DATE=$(ruby -e "require 'date';body=File.open('./content/now/index.md').read;match=body.match(/\*Updated on (.*)\*/);date=Date.parse(match[1]);puts date.strftime('%m-%d-%Y');")
  TODAY=$(ruby -e "require 'date';puts Date.today.strftime('%B %d, %Y');")
  mv $WEBSITE/content/now/index.md "./content/archives/now/${PREV_NOW_DATE}.md"
  touch $WEBSITE/content/now/index.md
  echo -e "\n\n*Updated on ${TODAY}*" >> $WEBSITE/content/now/index.md
  vim $WEBSITE/content/now/index.md
fi

if [ $1 = "money" ]; then
  THIS_MONTH=$(ruby -e "require ('date');date=Date.today.prev_month(1);puts date.strftime('%B-%Y').downcase;")
  PREV_MONTH=$(ruby -e "uequire ('date');date=Date.today.prev_month(2);puts date.strftime('%B-%Y').downcase;")
  cp "$WEBSITE/content/archives/statements/${PREV_MONTH}.md" "$WEBSITE/content/archives/statements/${THIS_MONTH}.md"
  vim "$WEBSITE/content/archives/statements/${THIS_MONTH}.md"
fi

if [ $1 = "install" ]; then
  ln -s $WEBSITE/me /usr/local/bin/me
fi
