version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: "Install & Build & Deploy"
          command: |
            gem install bundler -v 2.1.4
            bundle install
            gem install activesupport
            PROD=true ruby ./compiler/make.rb
            ./infra/deploy.sh
