version: 2.1
orbs:
  node: circleci/node@4.1.0

jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: "Install"
          command: |
            npm install
      - add_ssh_keys:
          fingerprints:
            - "d0:79:4b:17:1d:ac:53:46:69:30:96:4b:e2:af:8d:70"
      - run:
          name: "Build & Deploy"
          command: npm run deploy

workflows:
  build:
    jobs:
      - build:
        filters:
          branches:
            only:
              - main
