version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: "Install"
          command: |
            gem install bundler -v 2.1.4
            bundle install
      - add_ssh_keys
      - run:
          name: "Build & Deploy"
          command: |
            eval `ssh-agent`
            ssh-add ~/.ssh/id_rsa*
            /bin/bash ./infra/deploy.sh

workflows:
  version: 2
  deploy:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
